(jde-project-file-version "1.0")
(jde-set-variables
 '(jde-global-classpath (quote ("./bin" "./src" "./test" "./lib")))
 '(jde-compile-option-directory "./bin")
 '(jde-checkstyle-classpath (quote ("~/java/cvscheck/lib/checkstyle-all-4.4.jar" "./.cvscheck/checkstyle-extra-checks.jar")))
 '(jde-sourcepath (quote ("./src" "./test")))
 '(jde-checkstyle-expanded-properties (quote (("checkstyle.suppressions.file" . "/home/richard/sandbox/rtg/.cvscheck/checkstyle_suppressions.xml"))))
 '(jde-checkstyle-style "./.cvscheck/checkstyle_config.xml")
 '(jde-help-docsets (quote (("JDK API" "/usr/local/java/jdkdoc/docs/api" nil) ("User (javadoc)" "http://toru.rtg.18londonst.co.nz/keachecker/html/cvscheck_cartesian/javadocs/cartesian_src" nil) ("User (javadoc)" "http://intranet.nz.reeltwo.com/javadocs/junit3.8.1" nil))))
 '(jde-findbugs-exclude "./.cvscheck/findbugs_config.xml"))
